CREATE TABLE USUARIOS (
  ID SERIAL PRIMARY KEY NOT NULL,
  NOME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL, 
  SENHA VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) UNIQUE NOT NULL,
  DATA_DE_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PAIS VARCHAR(255) NOT NULL
);